"use client";
import { useCallback, useEffect, useState } from "react";
import MagicLinkLogin from "@/components/MagicLinkLogin";
import { supabase } from "@/lib/supabaseClient";
import AdminNavigation from "@/components/admin/AdminNavigation";
type Summary={store_id:string;store_name:string;today:number;month:number;total:number};
type Usage={id:string;store_id:string;user_id:string;reservation_id:string;used_at:string;coupons:{title:string}|null;coupon_stores:{store_name:string}|null};
export default function CouponUsageAdminPage(){
 const [access,setAccess]=useState<"loading"|"login"|"forbidden"|"ready"|"error">("loading"),[summary,setSummary]=useState<Summary[]>([]),[usages,setUsages]=useState<Usage[]>([]),[selected,setSelected]=useState("");
 const load=useCallback(async(storeId="")=>{const {data}=await supabase.auth.getSession();if(!data.session){setAccess("login");return}const response=await fetch(`/api/admin/coupon-usages${storeId?`?storeId=${encodeURIComponent(storeId)}`:""}`,{headers:{authorization:`Bearer ${data.session.access_token}`},cache:"no-store"});if(response.status===401){setAccess("login");return}if(response.status===403){setAccess("forbidden");return}if(!response.ok){setAccess("error");return}const result=await response.json();setSummary(result.summary);setUsages(result.usages);setAccess("ready")},[]);
 useEffect(()=>{void load()},[load]); const selectStore=(id:string)=>{setSelected(id);void load(id)};
 if(access==="loading")return <main className="members-admin"><p>管理者権限を確認中…</p></main>;if(access==="login")return <MagicLinkLogin next="/admin/coupon-usages" title="管理者ログイン"/>;if(access==="forbidden")return <main className="member-login"><div><p className="member-kicker">ADMIN ONLY</p><h1>クーポン利用実績</h1><p>管理者権限がありません。</p></div></main>;if(access==="error")return <main className="member-login"><div><h1>クーポン利用実績</h1><p>利用実績を読み込めませんでした。</p></div></main>;
 return <main className="members-admin coupon-admin"><AdminNavigation current="coupons"/><h1>クーポン利用実績</h1><p>店舗別の集計と、運営確認用の利用履歴です。</p><div className="coupon-admin-table"><table><thead><tr><th>店舗</th><th>今日</th><th>今月</th><th>累計</th></tr></thead><tbody>{summary.map(store=><tr key={store.store_id} className={selected===store.store_id?"is-selected":""}><th><button onClick={()=>selectStore(store.store_id)}>{store.store_name}</button></th><td>{store.today}</td><td>{store.month}</td><td>{store.total}</td></tr>)}</tbody></table></div>{selected&&<button className="coupon-admin-clear" onClick={()=>{setSelected("");void load()}}>全店舗の履歴に戻す</button>}<h2>{selected?`${summary.find(store=>store.store_id===selected)?.store_name??"店舗"}の履歴`:"最近の利用履歴"}</h2><div className="coupon-admin-history">{usages.length===0?<p>利用履歴はありません。</p>:usages.map(usage=><article key={usage.id}><div><time>{new Date(usage.used_at).toLocaleString("ja-JP")}</time><strong>{usage.coupon_stores?.store_name??"店舗"} — {usage.coupons?.title??"クーポン"}</strong></div><small>ユーザーID: {usage.user_id}<br/>予約ID: {usage.reservation_id}</small></article>)}</div></main>
}
