"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import AppMenu from "@/components/AppMenu";
import BingoGrid from "@/components/bingo/BingoGrid";
import { bingoLines } from "@/lib/bingo/lines";
import { supabase } from "@/lib/supabaseClient";
type Habit={id:string;position:number;name:string;target_count:number;count:number;loggedToday:boolean}; type Reward={line_count:number|null,reward_type:string;description:string};
const defaults=["筋トレ","読書","散歩","勉強","日記","早起き","掃除","自炊","ストレッチ"];
export default function HabitPage(){const [boardId,setBoardId]=useState<string|null>(null),[habits,setHabits]=useState<Habit[]>([]),[rewards,setRewards]=useState<Reward[]>([]),[names,setNames]=useState(defaults),[targets,setTargets]=useState(Array(9).fill(7)),[oneReward,setOneReward]=useState("ケーキを食べる"),[allReward,setAllReward]=useState("温泉旅行に行く"),[error,setError]=useState("");
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:b}=await supabase.from("habit_bingos").select("id").eq("user_id",user.id).eq("is_active",true).maybeSingle();if(!b)return;setBoardId(b.id);const [{data:h},{data:r},{data:l}]=await Promise.all([supabase.from("habits").select("id,position,name,target_count").eq("habit_bingo_id",b.id).order("position"),supabase.from("rewards").select("line_count,reward_type,description").eq("habit_bingo_id",b.id),supabase.from("habit_logs").select("habit_id,date,completed").eq("user_id",user.id).eq("completed",true)]);const today=new Date().toLocaleDateString("en-CA");setHabits((h??[]).map(x=>({...x,count:(l??[]).filter(y=>y.habit_id===x.id).length,loggedToday:(l??[]).some(y=>y.habit_id===x.id&&y.date===today)})));setRewards(r??[])}
 useEffect(()=>{void load()},[]);const clear=useMemo(()=>new Set(habits.map((h,i)=>h.count>=h.target_count?i:-1).filter(i=>i>=0)),[habits]);const lines=bingoLines(3,clear);
 async function create(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}if(names.some(x=>!x.trim())||targets.some(x=>x<1)){setError("9個すべての習慣名と目標回数を入力してください");return}const {data:b,error:e}=await supabase.from("habit_bingos").insert({user_id:user.id,title:"わたしのHabitBingo",is_active:true}).select("id").single();if(e||!b){setError("作成できませんでした");return}await supabase.from("habits").insert(names.map((name,i)=>({habit_bingo_id:b.id,position:i,name,target_count:targets[i]})));await supabase.from("rewards").insert([{habit_bingo_id:b.id,reward_type:"lines",line_count:1,description:oneReward},{habit_bingo_id:b.id,reward_type:"all_clear",line_count:null,description:allReward}]);await load()}
 async function toggle(h:Habit,date=new Date().toLocaleDateString("en-CA")){const {data:{user}}=await supabase.auth.getUser();if(!user)return;if(h.loggedToday)await supabase.from("habit_logs").delete().eq("habit_id",h.id).eq("user_id",user.id).eq("date",date);else await supabase.from("habit_logs").upsert({habit_id:h.id,user_id:user.id,date,completed:true},{onConflict:"habit_id,date"});await load()}
 return <main className="bingo-shell"><AppMenu current="habit-bingo"/><div className="bingo-wrap"><div className="bingo-brand">HABIT BINGO</div><h1 className="bingo-title">続けた先に、<br/>ごほうびを。</h1>{!boardId?<div className="bingo-card"><h2>9個の習慣を決めよう</h2>{names.map((n,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 90px",gap:8,marginBottom:8}}><input className="bingo-field" value={n} onChange={e=>setNames(x=>x.map((v,j)=>j===i?e.target.value:v))}/><input className="bingo-field" aria-label={`${n}の目標回数`} type="number" min="1" value={targets[i]} onChange={e=>setTargets(x=>x.map((v,j)=>j===i?Number(e.target.value):v))}/></div>)}<h3>ごほうび</h3><input className="bingo-field" value={oneReward} onChange={e=>setOneReward(e.target.value)} placeholder="1 BINGO"/><br/><br/><input className="bingo-field" value={allReward} onChange={e=>setAllReward(e.target.value)} placeholder="ALL CLEAR"/><p><button className="bingo-action" onClick={create}>HabitBingoを作る</button></p><p className="bingo-note">利用にはログインが必要です。</p></div>:<><div className="bingo-stats"><span>BINGO {lines.length}</span><span>ALL CLEARまで {9-clear.size}</span></div><BingoGrid size={3} cleared={clear} onSelect={i=>void toggle(habits[i])}>{habits.map(h=><span key={h.id}><b>{h.name}</b><span className="bingo-progress">{h.count>=h.target_count?"CLEAR ✓":`${h.count} / ${h.target_count}`}<br/>{h.loggedToday?"今日 ✓（取消）":"今日やった"}</span></span>)}</BingoGrid><div className="bingo-card"><h2>ごほうび</h2>{rewards.map((r,i)=><p key={i}><b>{r.reward_type==="all_clear"?"ALL CLEAR":`${r.line_count} BINGO`}</b> → {r.description}</p>)}</div><Link className="habit-edit-link" href="/habit/edit">✎ 習慣・目標回数・ごほうびを修正する</Link><div className="bingo-card" style={{marginTop:12}}><b>過去日の修正</b><p className="bingo-note">各習慣の記録は日付単位で保存され、同じ日は1回だけ加算されます。</p><input className="bingo-field" type="date" onChange={e=>{const h=habits[0];if(h&&e.target.value)void toggle({...h,loggedToday:false},e.target.value)}}/><p className="bingo-note">日付を選ぶと先頭の習慣に記録します（管理画面拡張用のMVP操作）。</p></div></>}{error&&<p className="bingo-error">{error}</p>}</div></main>}
