"use client";

import { useEffect, useMemo, useState } from "react";
import AdminNavigation from "@/components/admin/AdminNavigation";
import { supabase } from "@/lib/supabaseClient";

type Stay = { id: string; name: string; slug: string; subtitle: string | null; description: string | null; image_url: string | null; address: string | null; latitude: number | null; longitude: number | null; is_published: boolean; recommendations?: { count: number }[] };
type Category = { id: string; name: string };
type SpotRow = { id: string; name: string; latitude: number; longitude: number; address: string | null; google_maps_url: string | null; image_url: string | null; description: string | null; distance_label: string | null; walking_time: string | null; driving_time: string | null; business_hours: string | null; closed_days: string | null; website_url: string | null; instagram_url: string | null; is_published: boolean };
const emptyStay = { name: "", slug: "", subtitle: "宿主おすすめMAP", description: "", image_url: "", address: "", latitude: "", longitude: "", is_published: false };
const emptySpot = { id: "", name: "", latitude: "", longitude: "", address: "", google_maps_url: "", image_url: "", description: "", distance_label: "", walking_time: "", driving_time: "", business_hours: "", closed_days: "", website_url: "", instagram_url: "", host_comment: "", stay_id: "", category_ids: [] as string[], sort_order: 0, is_featured: false, is_published: true };

export default function StayMapsAdmin() {
  const [allowed, setAllowed] = useState<boolean | null>(null); const [stays, setStays] = useState<Stay[]>([]); const [spots, setSpots] = useState<SpotRow[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [stayForm, setStayForm] = useState<any>(emptyStay); const [spotForm, setSpotForm] = useState<any>(emptySpot); const [message, setMessage] = useState(""); const [search, setSearch] = useState(""); const [saving, setSaving] = useState(false);
  async function load() {
    const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setAllowed(false); return; }
    const { data: profile } = await supabase.from("profiles").select("is_admin").eq("id", auth.user.id).maybeSingle(); if (!profile?.is_admin) { setAllowed(false); return; } setAllowed(true);
    const [stayResult, spotResult, categoryResult] = await Promise.all([supabase.from("stays").select("*,recommendations:stay_recommendations(count)").order("created_at"), supabase.from("stay_spots").select("*").order("created_at", { ascending: false }), supabase.from("stay_spot_categories").select("id,name").order("sort_order")]);
    if (stayResult.error || spotResult.error || categoryResult.error) setMessage(`読み込みに失敗しました: ${(stayResult.error || spotResult.error || categoryResult.error)?.message}`);
    setStays((stayResult.data ?? []) as unknown as Stay[]); setSpots((spotResult.data ?? []) as SpotRow[]); setCategories((categoryResult.data ?? []) as Category[]);
  }
  useEffect(() => { void load(); }, []);
  const shownSpots = useMemo(() => spots.filter(spot => spot.name.toLowerCase().includes(search.toLowerCase())), [search, spots]);
  async function saveStay(event: React.FormEvent) { event.preventDefault(); setSaving(true); const payload = { ...stayForm, latitude: numberOrNull(stayForm.latitude), longitude: numberOrNull(stayForm.longitude), description: nullOrText(stayForm.description), subtitle: nullOrText(stayForm.subtitle), image_url: nullOrText(stayForm.image_url), address: nullOrText(stayForm.address) }; const id = payload.id; delete payload.id; const result = id ? await supabase.from("stays").update(payload).eq("id", id) : await supabase.from("stays").insert(payload); setMessage(result.error ? `保存できませんでした: ${result.error.message}` : "宿を保存しました"); if (!result.error) setStayForm(emptyStay); setSaving(false); await load(); }
  async function editSpot(spot: SpotRow) { const { data: recs } = await supabase.from("stay_recommendations").select("stay_id,host_comment,is_featured,sort_order,is_published").eq("spot_id", spot.id).limit(1); const { data: links } = await supabase.from("stay_spot_category_links").select("category_id").eq("spot_id", spot.id); setSpotForm({ ...spot, ...recs?.[0], category_ids: (links ?? []).map(link => link.category_id), latitude: String(spot.latitude), longitude: String(spot.longitude) }); document.getElementById("spot-editor")?.scrollIntoView({ behavior: "smooth" }); }
  async function saveSpot(event: React.FormEvent) { event.preventDefault(); if (!spotForm.stay_id || !spotForm.host_comment.trim()) { setMessage("宿と宿主のひとことを入力してください"); return; } setSaving(true); const fields = ["name","address","google_maps_url","image_url","description","distance_label","walking_time","driving_time","business_hours","closed_days","website_url","instagram_url"] as const; const payload: any = { latitude: Number(spotForm.latitude), longitude: Number(spotForm.longitude), is_published: spotForm.is_published }; fields.forEach(key => payload[key] = key === "name" ? spotForm[key].trim() : nullOrText(spotForm[key])); let spotId = spotForm.id; const result = spotId ? await supabase.from("stay_spots").update(payload).eq("id", spotId).select("id").single() : await supabase.from("stay_spots").insert(payload).select("id").single(); if (result.error || !result.data) { setMessage(`保存できませんでした: ${result.error?.message}`); setSaving(false); return; } spotId = result.data.id; await supabase.from("stay_spot_category_links").delete().eq("spot_id", spotId); if (spotForm.category_ids.length) await supabase.from("stay_spot_category_links").insert(spotForm.category_ids.map((category_id: string) => ({ spot_id: spotId, category_id })));
    const recommendation = await supabase.from("stay_recommendations").upsert({ stay_id: spotForm.stay_id, spot_id: spotId, host_comment: spotForm.host_comment.trim(), is_featured: spotForm.is_featured, is_published: spotForm.is_published, sort_order: Number(spotForm.sort_order) || 0 }); setMessage(recommendation.error ? `おすすめを保存できませんでした: ${recommendation.error.message}` : "スポットを保存しました"); if (!recommendation.error) setSpotForm(emptySpot); setSaving(false); await load(); }
  async function removeSpot(id: string) { if (!window.confirm("このスポットを削除しますか？複数の宿で使われている場合も削除されます。")) return; const { error } = await supabase.from("stay_spots").delete().eq("id", id); setMessage(error ? `削除できませんでした: ${error.message}` : "削除しました"); await load(); }
  if (allowed === null) return <main className="admin-dashboard-state">管理者権限を確認しています…</main>; if (!allowed) return <main className="admin-dashboard-state">管理者としてログインしてください。</main>;
  return <main className="stay-admin"><AdminNavigation current="stay-maps"/><header><div><span>LOCAL GUIDE CMS</span><h1>宿専用おすすめMAP</h1></div><p>宿主だから知っている場所を、宿泊者へ。</p></header>{message && <p className="stay-admin-message" role="status">{message}</p>}
    <section className="stay-admin-panel"><h2>宿一覧</h2><div className="stay-admin-grid">{stays.map(stay => <article key={stay.id}><span>{stay.is_published ? "● 公開中" : "○ 非公開"}</span><h3>{stay.name}</h3><p>/{stay.slug} · {stay.recommendations?.[0]?.count ?? 0} spots</p><div><button onClick={() => setStayForm({ ...stay, latitude: stay.latitude ?? "", longitude: stay.longitude ?? "" })}>編集</button><a href={`/stay/${stay.slug}`} target="_blank">MAPを見る ↗</a></div>{stay.is_published && <div className="stay-admin-qr"><img src={qrUrl(mapUrl(stay.slug))} alt={`${stay.name}のMAP QRコード`}/><a href={qrUrl(mapUrl(stay.slug), 700)} download={`${stay.slug}-map-qr.png`}>QRをPNG表示・保存</a></div>}</article>)}</div>
      <form className="stay-admin-form" onSubmit={saveStay}><h3>{stayForm.id ? "宿を編集" : "新しい宿"}</h3><label>宿名<input required value={stayForm.name} onChange={e => setStayForm({ ...stayForm, name: e.target.value })}/></label><label>slug<input required pattern="[a-z0-9][a-z0-9-]*" value={stayForm.slug} onChange={e => setStayForm({ ...stayForm, slug: e.target.value })}/></label><label>サブタイトル<input value={stayForm.subtitle || ""} onChange={e => setStayForm({ ...stayForm, subtitle: e.target.value })}/></label><label className="wide">説明<textarea rows={3} value={stayForm.description || ""} onChange={e => setStayForm({ ...stayForm, description: e.target.value })}/></label><label className="wide">メイン写真URL<input type="url" value={stayForm.image_url || ""} onChange={e => setStayForm({ ...stayForm, image_url: e.target.value })}/></label><label className="wide">住所<input value={stayForm.address || ""} onChange={e => setStayForm({ ...stayForm, address: e.target.value })}/></label><label>緯度<input type="number" step="any" value={stayForm.latitude} onChange={e => setStayForm({ ...stayForm, latitude: e.target.value })}/></label><label>経度<input type="number" step="any" value={stayForm.longitude} onChange={e => setStayForm({ ...stayForm, longitude: e.target.value })}/></label><label className="check"><input type="checkbox" checked={stayForm.is_published} onChange={e => setStayForm({ ...stayForm, is_published: e.target.checked })}/>公開する</label><button disabled={saving}>宿を保存</button></form></section>
    <section className="stay-admin-panel" id="spot-editor"><div className="stay-admin-title"><h2>スポット</h2><input type="search" placeholder="店名で検索" value={search} onChange={e => setSearch(e.target.value)}/></div><form className="stay-admin-form" onSubmit={saveSpot}><h3>{spotForm.id ? "スポットを編集" : "スポットをすばやく追加"}</h3><label>店名・スポット名<input required value={spotForm.name} onChange={e => setSpotForm({ ...spotForm, name: e.target.value })}/></label><label>宿<select required value={spotForm.stay_id} onChange={e => setSpotForm({ ...spotForm, stay_id: e.target.value })}><option value="">選択してください</option>{stays.map(stay => <option key={stay.id} value={stay.id}>{stay.name}</option>)}</select></label><label>緯度<input required type="number" min="-90" max="90" step="any" value={spotForm.latitude} onChange={e => setSpotForm({ ...spotForm, latitude: e.target.value })}/></label><label>経度<input required type="number" min="-180" max="180" step="any" value={spotForm.longitude} onChange={e => setSpotForm({ ...spotForm, longitude: e.target.value })}/></label><label className="wide">Google Maps URL<input type="url" value={spotForm.google_maps_url || ""} onChange={e => setSpotForm({ ...spotForm, google_maps_url: e.target.value })}/></label><label className="wide">宿主のひとこと<textarea required maxLength={1000} rows={4} value={spotForm.host_comment} onChange={e => setSpotForm({ ...spotForm, host_comment: e.target.value })}/></label><fieldset className="wide"><legend>カテゴリ（複数選択可）</legend>{categories.map(cat => <label className="check" key={cat.id}><input type="checkbox" checked={spotForm.category_ids.includes(cat.id)} onChange={e => setSpotForm({ ...spotForm, category_ids: e.target.checked ? [...spotForm.category_ids, cat.id] : spotForm.category_ids.filter((id: string) => id !== cat.id) })}/>{cat.name}</label>)}</fieldset>{([['image_url','写真URL'],['address','住所'],['description','簡単な説明'],['distance_label','距離'],['walking_time','徒歩時間'],['driving_time','車の時間'],['business_hours','営業時間'],['closed_days','定休日'],['website_url','WebサイトURL'],['instagram_url','Instagram URL']] as const).map(([key,label]) => <label key={key}>{label}<input value={spotForm[key] || ""} onChange={e => setSpotForm({ ...spotForm, [key]: e.target.value })}/></label>)}<label>並び順<input type="number" value={spotForm.sort_order} onChange={e => setSpotForm({ ...spotForm, sort_order: e.target.value })}/></label><label className="check"><input type="checkbox" checked={spotForm.is_featured} onChange={e => setSpotForm({ ...spotForm, is_featured: e.target.checked })}/>★ 宿主おすすめ</label><label className="check"><input type="checkbox" checked={spotForm.is_published} onChange={e => setSpotForm({ ...spotForm, is_published: e.target.checked })}/>表示する</label><div className="wide"><button disabled={saving}>スポットを保存</button>{spotForm.id && <button type="button" className="secondary" onClick={() => setSpotForm(emptySpot)}>キャンセル</button>}</div></form>
      <div className="stay-admin-table">{shownSpots.map(spot => <article key={spot.id}><div><span>{spot.is_published ? "公開" : "非公開"}</span><h3>{spot.name}</h3><p>{spot.address || `${spot.latitude}, ${spot.longitude}`}</p></div><button onClick={() => void editSpot(spot)}>編集</button><button className="danger" onClick={() => void removeSpot(spot.id)}>削除</button></article>)}</div></section>
  </main>;
}
function nullOrText(value: unknown) { const text = String(value ?? "").trim(); return text || null; } function numberOrNull(value: unknown) { return value === "" || value == null ? null : Number(value); }
function qrUrl(value: string, size = 240) { return `https://quickchart.io/qr?size=${size}&margin=2&text=${encodeURIComponent(value)}`; }
function mapUrl(slug: string) { return `${typeof window === "undefined" ? "https://photomappaer.com" : window.location.origin}/stay/${slug}`; }
