-- Standalone-friendly TownBingo and HabitBingo domain.
alter table public.profiles add column if not exists is_admin boolean not null default false;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select coalesce((select is_admin from profiles where id=auth.uid()),false)$$;

-- Public map content is now managed by administrators only. Existing rows are untouched.
drop policy if exists places_rw on public.places; drop policy if exists places_insert_member on public.places; drop policy if exists places_update_member on public.places; drop policy if exists places_delete_member on public.places; drop policy if exists places_insert_authenticated on public.places; drop policy if exists places_update_own on public.places; drop policy if exists places_delete_own on public.places;
create policy places_admin_insert on public.places for insert to authenticated with check(public.is_admin());
create policy places_admin_update on public.places for update to authenticated using(public.is_admin()) with check(public.is_admin());
create policy places_admin_delete on public.places for delete to authenticated using(public.is_admin());

create table public.bingos(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,municipality_name text not null,description text,cover_image_url text,is_published boolean not null default false,created_by uuid references auth.users,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.bingo_items(id uuid primary key default gen_random_uuid(),bingo_id uuid not null references public.bingos on delete cascade,position int not null check(position>=0),type text not null check(type in('photo','quiz')),title text not null,description text,question text,hint text,correct_answers text[],spot_id uuid references public.places on delete set null,photo_required boolean not null default false,sort_order int not null default 0,unique(bingo_id,position));
create table public.bingo_sessions(id uuid primary key default gen_random_uuid(),bingo_id uuid not null references public.bingos on delete cascade,user_id uuid not null references auth.users on delete cascade,start_time timestamptz not null default now(),completed_at timestamptz,status text not null default 'active' check(status in('active','completed','abandoned')),created_at timestamptz not null default now());
create table public.bingo_progress(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.bingo_sessions on delete cascade,bingo_item_id uuid not null references public.bingo_items on delete cascade,is_cleared boolean not null default false,answer text,photo_url text,cleared_at timestamptz,unique(session_id,bingo_item_id));
create table public.habit_bingos(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,title text not null,is_active boolean not null default true,created_at timestamptz not null default now());
create unique index one_active_habit_bingo on public.habit_bingos(user_id) where is_active;
create table public.habits(id uuid primary key default gen_random_uuid(),habit_bingo_id uuid not null references public.habit_bingos on delete cascade,position int not null check(position between 0 and 8),name text not null,target_count int not null check(target_count>0),unique(habit_bingo_id,position));
create table public.habit_logs(id uuid primary key default gen_random_uuid(),habit_id uuid not null references public.habits on delete cascade,user_id uuid not null references auth.users on delete cascade,date date not null,completed boolean not null default true,created_at timestamptz not null default now(),unique(habit_id,date));
create table public.rewards(id uuid primary key default gen_random_uuid(),habit_bingo_id uuid not null references public.habit_bingos on delete cascade,reward_type text not null check(reward_type in('lines','all_clear')),line_count int,description text not null,created_at timestamptz not null default now());

alter table public.bingos enable row level security;alter table public.bingo_items enable row level security;alter table public.bingo_sessions enable row level security;alter table public.bingo_progress enable row level security;alter table public.habit_bingos enable row level security;alter table public.habits enable row level security;alter table public.habit_logs enable row level security;alter table public.rewards enable row level security;
create policy bingos_read on public.bingos for select using(is_published or public.is_admin());create policy bingos_admin on public.bingos for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy items_read on public.bingo_items for select using(exists(select 1 from bingos b where b.id=bingo_id and (b.is_published or public.is_admin())));create policy items_admin on public.bingo_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy sessions_own on public.bingo_sessions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy progress_own on public.bingo_progress for all to authenticated using(exists(select 1 from bingo_sessions s where s.id=session_id and s.user_id=auth.uid())) with check(exists(select 1 from bingo_sessions s where s.id=session_id and s.user_id=auth.uid()));
create policy habit_bingos_own on public.habit_bingos for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy habits_own on public.habits for all to authenticated using(exists(select 1 from habit_bingos b where b.id=habit_bingo_id and b.user_id=auth.uid())) with check(exists(select 1 from habit_bingos b where b.id=habit_bingo_id and b.user_id=auth.uid()));
create policy logs_own on public.habit_logs for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid() and exists(select 1 from habits h join habit_bingos b on b.id=h.habit_bingo_id where h.id=habit_id and b.user_id=auth.uid()));
create policy rewards_own on public.rewards for all to authenticated using(exists(select 1 from habit_bingos b where b.id=habit_bingo_id and b.user_id=auth.uid())) with check(exists(select 1 from habit_bingos b where b.id=habit_bingo_id and b.user_id=auth.uid()));
insert into storage.buckets(id,name,public) values('bingo-photos','bingo-photos',false) on conflict(id) do nothing;
create policy bingo_photo_insert on storage.objects for insert to authenticated with check(bucket_id='bingo-photos' and exists(select 1 from bingo_sessions s where s.id=(storage.foldername(name))[1]::uuid and s.user_id=auth.uid()));
create policy bingo_photo_read on storage.objects for select to authenticated using(bucket_id='bingo-photos' and exists(select 1 from bingo_sessions s where s.id=(storage.foldername(name))[1]::uuid and s.user_id=auth.uid()));

-- A complete editable Daigo starter board: ratio is data, not schema-enforced.
with b as (insert into public.bingos(slug,title,municipality_name,description,is_published) values('daigo','大子町まち歩きBINGO','大子町','景色を撮り、街の答えを探す25のミッション。',true) on conflict(slug) do update set title=excluded.title returning id)
insert into public.bingo_items(bingo_id,position,type,title,description,question,hint,correct_answers,photo_required,sort_order)
select b.id,n,case when n<10 then 'photo' else 'quiz' end,case when n<10 then '大子の一枚 '||(n+1) else '街のクイズ '||(n-9) end,case when n<10 then '大子町で心に残った風景を撮影してください。' else '現地の案内を探して答えてください。' end,case when n>=10 then '案内板に書かれたキーワードは？' end,case when n>=10 then '近くの案内板を確認しよう' end,case when n>=10 then array['だいご','大子'] end,n<10,n from b cross join generate_series(0,24)n on conflict(bingo_id,position) do nothing;
